# Generated by Django 5.2.15 on 2026-06-11 15:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(db_index=True, max_length=20)),
                ('code', models.CharField(max_length=6)),
                ('verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('buyer', 'Покупатель'), ('seller', 'Продавец')], default='buyer', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('sim_verified', models.BooleanField(default=False)),
                ('sim_id', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(default='Almaty', max_length=80)),
                ('age', models.PositiveIntegerField(default=18)),
                ('interests', models.JSONField(blank=True, default=list)),
                ('budget_usd', models.PositiveIntegerField(default=100)),
                ('currency_preference', models.CharField(default='KZT', max_length=4)),
                ('language', models.CharField(default='ru', max_length=4)),
                ('shop_name', models.CharField(blank=True, max_length=120)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('marketplace', models.CharField(default='AliExpress', max_length=40)),
                ('category', models.CharField(default='Electronics', max_length=40)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('price_individual', models.FloatField()),
                ('price_group_min', models.FloatField()),
                ('group_threshold', models.PositiveIntegerField(default=10)),
                ('image_url', models.CharField(blank=True, max_length=600)),
                ('rating', models.FloatField(default=4.5)),
                ('origin_country', models.CharField(default='China', max_length=60)),
                ('source_id', models.CharField(blank=True, max_length=120, null=True)),
                ('source_url', models.CharField(blank=True, max_length=600, null=True)),
                ('source_price', models.FloatField(blank=True, null=True)),
                ('source_currency', models.CharField(blank=True, max_length=12, null=True)),
                ('source_location', models.CharField(blank=True, max_length=120, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(max_length=24, primary_key=True, serialize=False)),
                ('current_members', models.PositiveIntegerField(default=0)),
                ('threshold', models.PositiveIntegerField(default=10)),
                ('price_current', models.FloatField()),
                ('price_individual', models.FloatField()),
                ('expires_at', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('active', 'Активна'), ('completed', 'Собрана'), ('expired', 'Истекла')], default='active', max_length=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='api.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('group', 'user')},
            },
        ),
    ]
